name: CI

on:
  push:
    branches: [ "main" ]


jobs:
  builds:
    run-on: ubuntu-latest

    steps:
    - name: "Checkout SCM"
      uses: actions/checkout@v4
      with:
        repository: aidynilyas/actions-feb-cicd

    - name: Test
      uses: ls